### ISSUE TITLE
Добавить примеры подключения медиаресурсовов

### ISSUE THREAD

**Issue by nikolai-shabalin** [htmlacademy/html2-basic-template#64]
Показать с какими путями подключить:
- всевозможное фавиконки, из корня и из папки
- стили к странице
- изображения: контентные и декоративные в стилях
- шрифты в стилях
- другое

**Comment by firefoxic** [comment]
Кажется избыточным. Это так мы просто за студентов работу сделаем, они тупо копипастить будут.
То, где какие файлы должны лежать — уже есть в ридмишках.
Достаточно будет лишь пояснить, что пути надо писать:
- относительные от текущего файла с кодом (может пояснить про `./` и `../`, хотя это в материалах курсов должно быть, а не тут);
- ориентироваться надо на расположение исходных файлов, а не билда, то есть можно использовать подсказки редактора.

**Comment by firefoxic** [comment]
Пусть привыкают сами писать пути. Там же просто всё: точка слэш вниз вниз вниз энтер — готово.

**Comment by nikolai-shabalin** [comment]
Они и не прочитают этот ридми. Сборка используется не только на курсе HTML2. 
Поэтому студенты курса в теории узнают как работают пути и какие есть в сборке. 
А остальные смогут почитать доку(ридми)

**Comment by firefoxic** [comment]
Что-то вроде того, что на скриншоте в #77?
Могу добавить в PR 👀

**Comment by nikolai-shabalin** [comment]
Примерно так, только пример должен быть исключительно про медиаресурс, то есть весь обвес не важный для примера удалить.

Пример
```scss
.header {
  background-color: #000000;
  color: #ffffff;
  padding: 10px 15px;
  background-image: url("../../images/vs.svg");
}
```

можно сократить до 
```scss
.header {
  background-image: url("../../images/vs.svg");
}
```

Нужно добавить примеры для:
- растровая графика: добавление в разметке и стилях
- векторная графика: добавление в разметке и стилях
- спрайт: добавление в разметке и стилях
- шрифты: добавление в стилях
